// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3172.RalphTheWonderLlamaWPIOnly.subsystems;

import org.usfirst.frc3172.RalphTheWonderLlamaWPIOnly.RobotMap;
import org.usfirst.frc3172.RalphTheWonderLlamaWPIOnly.commands.TankDrive;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class DriveChain extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private final SpeedController left1 = RobotMap.driveChainleft1;
	private final SpeedController right1 = RobotMap.driveChainright1;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	double max = 1;// .8
	double min = -1;// -.8
	double enhancer = 1;// 0.7;

	public void switchcontrols() {
		enhancer = enhancer * -1;
	}

	public void tankDriveLeft(Joystick Gamepad) {

		if (Gamepad.getRawAxis(1) < max && Gamepad.getRawAxis(1) > min) {
			left1.set((Math.round(Gamepad.getRawAxis(1) * 10 ) / 10) * enhancer);// to change speed add
			// *.8,.5,.3.etc. With /20,
			// should be 5 different
			// speed settings.
			// System.out.println("left in range");
		} else if (Gamepad.getRawAxis(1) > max) {
			left1.set(max * enhancer);
			// System.out.println("left less");
		} else if (Gamepad.getRawAxis(1) < min) {
			left1.set(min * enhancer);
			// System.out.println("left over");
		}
	}

	public void tankDriveRight(Joystick Gamepad) {

		if (Gamepad.getRawAxis(5) < max && Gamepad.getRawAxis(5) > min) {
			right1.set((Math.round(Gamepad.getRawAxis(5) * 10 ) / 10) * enhancer);//to keep from equaling .01 etc.
			// *.8,.5,.3.etc. With /20,
			// should be 5 different
			// speed settings.
			// System.out.println("right in range");
		} else if (Gamepad.getRawAxis(5) > max) {
			right1.set(max * enhancer);
			// System.out.println("right less");
		} else if (Gamepad.getRawAxis(5) < min) {
			right1.set(min * enhancer);
			// System.out.println("right over");
		}
	}

	public void stop() {
		// System.out.println("stopping");
		left1.set(0);
		right1.set(0);
	}

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		setDefaultCommand(new TankDrive());

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}
}
